#  Grid-Searching Which Model To Use

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

pipe = Pipeline([('preprocessing', StandardScaler()), ('classifier', SVC())])

In [3]:
from sklearn.ensemble import RandomForestClassifier

param_grid = [
    {'classifier': [SVC()], 
     'preprocessing': [StandardScaler(), None],
     'classifier__gamma': [0.001, 0.01, 0.1, 1, 10, 100],
     'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]},
    {'classifier': [RandomForestClassifier(n_estimators=100)],
     'preprocessing': [None], 
     'classifier__max_features': [1, 2, 3]}]

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV

cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, random_state=0)

grid = GridSearchCV(pipe, param_grid, cv=5)
grid.fit(X_train, y_train)

print(f"Best params:\n{grid.best_params_}\n")
print(f"Best cross-validation score: {grid.best_score_:.2f}")
print(f"Test-set score: {grid.score(X_test, y_test):.2f}")

Best params:
{'classifier': SVC(C=10, gamma=0.01), 'classifier__C': 10, 'classifier__gamma': 0.01, 'preprocessing': StandardScaler()}

Best cross-validation score: 0.99
Test-set score: 0.98


## Vaja

In [43]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, Normalizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [14]:
iris_df=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_df.data ,iris_df.target, test_size=0.2, random_state=0)

In [18]:
pipeline_lr = make_pipeline(StandardScaler(), PCA(n_components=2), LogisticRegression(random_state=0))
model = pipeline_lr.fit(X_train, y_train)
final_score = model.score(X_test,y_test)
print(f"Final score - {model.steps}: {final_score:.2}")

Final score - [('standardscaler', StandardScaler()), ('pca', PCA(n_components=2)), ('logisticregression', LogisticRegression(random_state=0))]: 0.87


In [78]:
def run_grid_pipeline_iris_df():
    iris_df = load_iris()
    X_train, X_test, y_train, y_test = train_test_split(iris_df.data ,iris_df.target, test_size=0.25, random_state=0)
    
    # start pipeline
    pipe = Pipeline([('preprocessing_scaling', StandardScaler()), 
                     ('predprocessing_pca', PCA()),
                     ('classifier', LogisticRegression(random_state=0))])

    # PARAMETERS
    param_grid = [
        {'classifier': [LogisticRegression(max_iter=10000, solver="saga")], 
         'predprocessing_pca': [PCA(n_components=2), None],
         'preprocessing_scaling': [MinMaxScaler(), StandardScaler(), RobustScaler(), Normalizer(), None],
         'classifier__penalty': ["l1", "l2"], 
        },
        {'classifier': [DecisionTreeClassifier(random_state=0)], 
         'predprocessing_pca': [PCA(n_components=2), None],
         'preprocessing_scaling': [MinMaxScaler(), StandardScaler(), RobustScaler(), Normalizer(), None],  
        },
        {'classifier': [SVC()], 
         'predprocessing_pca': [PCA(n_components=2), None],
         'preprocessing_scaling': [MinMaxScaler(), StandardScaler(), RobustScaler(), Normalizer(), None],
        },
        {'classifier': [KNeighborsClassifier()], 
         'predprocessing_pca': [PCA(n_components=2), None],
         'preprocessing_scaling': [MinMaxScaler(), StandardScaler(), RobustScaler(), Normalizer(), None],
        },
    ]

    # run grid search
    grid = GridSearchCV(pipe, param_grid, cv=5)
    grid.fit(X_train, y_train)
    
    print(f"Best params:\n{grid.best_params_}\n")
    print(f"Test-set score: {grid.score(X_test, y_test):.2f}")
    results = pd.DataFrame(grid.cv_results_)
    # confusion matrix
    prediction = grid.predict(X_test)
    confusion = confusion_matrix(y_test, prediction)
    print(f"Confusion matrix:\n{confusion}\n")
    return results

In [81]:
grids_result = run_grid_pipeline_iris_df()

Best params:
{'classifier': DecisionTreeClassifier(random_state=0), 'predprocessing_pca': PCA(n_components=2), 'preprocessing_scaling': Normalizer()}

Test-set score: 0.97
Confusion matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]



In [82]:
grids_result

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.003285      0.000565         0.000699        0.000076   
1        0.004829      0.000347         0.000686        0.000032   
2        0.005521      0.000315         0.000676        0.000013   
3        0.003535      0.000384         0.000803        0.000024   
4        0.004960      0.000280         0.000551        0.000019   
5        0.017072      0.005978         0.000556        0.000022   
6        0.019870      0.005984         0.000620        0.000125   
7        0.017269      0.003563         0.000563        0.000023   
8        0.004160      0.000122         0.000613        0.000010   
9        0.120960      0.017948         0.000422        0.000013   
10       0.002583      0.000051         0.000634        0.000021   
11       0.003165      0.000061         0.000646        0.000026   
12       0.004153      0.000049         0.000629        0.000006   
13       0.002619      0.000067         0.000735        0.000020   
14       0.003109      0.000075         0.000518        0.000010   
15       0.002516      0.000082         0.000525        0.000021   
16       0.003441      0.000063         0.000509        0.000001   
17       0.004280      0.000069         0.000509        0.000001   
18       0.002433      0.000116         0.000608        0.000002   
19       0.060802      0.001859         0.000396        0.000001   
20       0.001874      0.000142         0.000651        0.000021   
21       0.001967      0.000050         0.000681        0.000032   
22       0.003322      0.000023         0.000651        0.000019   
23       0.001731      0.000008         0.000756        0.000018   
24       0.001433      0.000017         0.000525        0.000001   
25       0.001396      0.000022         0.000530        0.000019   
26       0.001590      0.000034         0.000523        0.000001   
27       0.002925      0.000047         0.000545        0.000022   
28       0.001462      0.000059         0.000648        0.000039   
29       0.001044      0.000020         0.000420        0.000029   
30       0.001873      0.000128         0.000771        0.000034   
31       0.002013      0.000013         0.000740        0.000011   
32       0.003416      0.000062         0.000760        0.000021   
33       0.001791      0.000034         0.000862        0.000040   
34       0.001457      0.000033         0.000621        0.000018   
35       0.001407      0.000026         0.000618        0.000016   
36       0.001672      0.000019         0.000617        0.000004   
37       0.003039      0.000036         0.000647        0.000028   
38       0.001476      0.000047         0.000753        0.000021   
39       0.001020      0.000047         0.000483        0.000023   
40       0.001497      0.000086         0.002427        0.000197   
41       0.001682      0.000214         0.002432        0.000051   
42       0.002827      0.000066         0.002345        0.000053   
43       0.001423      0.000054         0.002411        0.000085   
44       0.001091      0.000015         0.002267        0.000052   
45       0.001043      0.000012         0.002245        0.000058   
46       0.001251      0.000022         0.002176        0.000042   
47       0.002436      0.000031         0.002209        0.000040   
48       0.001095      0.000020         0.002267        0.000033   
49       0.000763      0.000022         0.002077        0.000022   

                                     param_classifier  \
0   LogisticRegression(max_iter=10000, solver='saga')   
1   LogisticRegression(max_iter=10000, solver='saga')   
2   LogisticRegression(max_iter=10000, solver='saga')   
3   LogisticRegression(max_iter=10000, solver='saga')   
4   LogisticRegression(max_iter=10000, solver='saga')   
5   LogisticRegression(max_iter=10000, solver='saga')   
6   LogisticRegression(max_iter=10000, solver='saga')   
7   LogisticRegression(max_iter=10000, solver='saga')   
8   LogisticRegression